import { User, LeaderboardUser } from "@/types/user";
import { Discussion, FeaturedDiscussion, VibingItem, Campaign } from "@/types/discussion";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Alex Chen",
    handle: "@alexchen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    verified: true,
    points: 12500,
  },
  {
    id: "2",
    name: "Sarah Miller",
    handle: "@sarahm",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    verified: true,
    points: 9800,
  },
  {
    id: "3",
    name: "James Wilson",
    handle: "@jwilson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=james",
    points: 7200,
  },
  {
    id: "4",
    name: "Emma Davis",
    handle: "@emmad",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=emma",
    verified: true,
    points: 5600,
  },
  {
    id: "5",
    name: "Michael Brown",
    handle: "@mikeb",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=michael",
    points: 4300,
  },
  {
    id: "6",
    name: "Lisa Johnson",
    handle: "@lisaj",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=lisa",
    points: 3800,
  },
  {
    id: "7",
    name: "David Lee",
    handle: "@davidl",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=david",
    verified: true,
    points: 3200,
  },
  {
    id: "8",
    name: "Jennifer Park",
    handle: "@jenp",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jennifer",
    points: 2900,
  },
];

export const mockLeaderboard: LeaderboardUser[] = [
  {
    ...mockUsers[0],
    rank: 1,
    points: 12500,
    badge: "gold",
    weeklyChange: 15,
  },
  {
    ...mockUsers[1],
    rank: 2,
    points: 9800,
    badge: "silver",
    weeklyChange: 8,
  },
  {
    ...mockUsers[2],
    rank: 3,
    points: 7200,
    badge: "bronze",
    weeklyChange: -3,
  },
];

export const mockDiscussions: Discussion[] = [
  {
    id: "1",
    title: "Claude 3.5 Sonnet is a game changer for coding assistants",
    summary: "After extensive testing, Claude 3.5 Sonnet demonstrates remarkable improvements in code understanding, generation accuracy, and contextual awareness. The model shows particular strength in complex refactoring tasks.",
    author: mockUsers[0],
    category: "review",
    createdAt: "2h ago",
    upvotes: 342,
    comments: 89,
    participants: [mockUsers[1], mockUsers[2], mockUsers[3], mockUsers[4], mockUsers[5]],
    previewImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=200&fit=crop",
    tags: ["AI", "Claude", "Coding"],
  },
  {
    id: "2",
    title: "Midjourney V6 vs DALL-E 3: Comprehensive comparison for professional workflows",
    summary: "A detailed side-by-side analysis of both image generators across various use cases including product photography, concept art, and marketing materials. Includes prompt engineering tips for each platform.",
    author: mockUsers[1],
    category: "compare",
    createdAt: "4h ago",
    upvotes: 256,
    comments: 67,
    participants: [mockUsers[0], mockUsers[2], mockUsers[4]],
    tags: ["Midjourney", "DALL-E", "Image Generation"],
  },
  {
    id: "3",
    title: "Building a $10k/month SaaS with AI tools: My complete tech stack",
    summary: "From idea to revenue in 90 days. I share the exact AI tools, frameworks, and automation workflows I used to build and launch my SaaS product. Includes cost breakdown and lessons learned.",
    author: mockUsers[2],
    category: "showcase",
    createdAt: "6h ago",
    upvotes: 512,
    comments: 134,
    participants: [mockUsers[0], mockUsers[1], mockUsers[3], mockUsers[5], mockUsers[6], mockUsers[7]],
    previewImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=200&fit=crop",
    tags: ["SaaS", "Startup", "AI Tools"],
  },
  {
    id: "4",
    title: "The ultimate guide to fine-tuning LLMs for your specific use case",
    summary: "Step-by-step tutorial covering data preparation, training strategies, evaluation metrics, and deployment. Includes code examples for both OpenAI and open-source models.",
    author: mockUsers[3],
    category: "tutorial",
    createdAt: "8h ago",
    upvotes: 189,
    comments: 45,
    participants: [mockUsers[0], mockUsers[2]],
    tags: ["LLM", "Fine-tuning", "Tutorial"],
  },
  {
    id: "5",
    title: "OpenAI announces GPT-5 preview at developer conference",
    summary: "Breaking news from the OpenAI Dev Day: GPT-5 preview shows significant improvements in reasoning, multimodal capabilities, and reduced hallucinations. Limited access begins next month.",
    author: mockUsers[4],
    category: "news",
    createdAt: "1h ago",
    upvotes: 876,
    comments: 234,
    participants: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[3], mockUsers[5], mockUsers[6]],
    previewImage: "https://images.unsplash.com/photo-1676299081847-c5162e2f5c3a?w=400&h=200&fit=crop",
    tags: ["OpenAI", "GPT-5", "News"],
  },
  {
    id: "6",
    title: "Help needed: Best practices for AI-generated content moderation",
    summary: "Looking for advice on implementing content moderation for AI outputs in a production environment. Interested in both automated solutions and human-in-the-loop approaches.",
    author: mockUsers[5],
    category: "help",
    createdAt: "3h ago",
    upvotes: 45,
    comments: 28,
    participants: [mockUsers[1], mockUsers[3]],
    tags: ["Moderation", "Safety", "Help"],
  },
  {
    id: "7",
    title: "Top 10 AI productivity tools that actually save time in 2024",
    summary: "After testing 50+ tools, here's my curated list of AI assistants that genuinely improve workflow efficiency. Each tool is rated on ease of use, integration capabilities, and ROI.",
    author: mockUsers[6],
    category: "list",
    createdAt: "12h ago",
    upvotes: 423,
    comments: 98,
    participants: [mockUsers[0], mockUsers[2], mockUsers[4], mockUsers[5]],
    tags: ["Productivity", "Tools", "List"],
  },
  {
    id: "8",
    title: "Local LLMs are finally ready for production: Here's the proof",
    summary: "Benchmarks and real-world performance tests showing how Llama 3, Mistral, and other open models can match or exceed GPT-3.5 for many tasks while running entirely on your own infrastructure.",
    author: mockUsers[7],
    category: "review",
    createdAt: "5h ago",
    upvotes: 298,
    comments: 76,
    participants: [mockUsers[0], mockUsers[1], mockUsers[2]],
    previewImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=200&fit=crop",
    tags: ["Local LLM", "Open Source", "Review"],
  },
];

export const mockFeaturedDiscussions: FeaturedDiscussion[] = [
  {
    id: "f1",
    title: "The Future of AI-Powered Creative Tools",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop",
    category: "Featured",
    author: mockUsers[0],
    gradient: "from-indigo-600 to-purple-600",
  },
  {
    id: "f2",
    title: "Building Autonomous Agents with LangChain",
    image: "https://images.unsplash.com/photo-1676299081847-c5162e2f5c3a?w=600&h=400&fit=crop",
    category: "Tutorial",
    author: mockUsers[1],
    gradient: "from-purple-600 to-pink-600",
  },
  {
    id: "f3",
    title: "AI Ethics: A Community Discussion",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&h=400&fit=crop",
    category: "Debate",
    author: mockUsers[2],
    gradient: "from-pink-600 to-rose-600",
  },
  {
    id: "f4",
    title: "Scaling AI Startups: Lessons Learned",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop",
    category: "Showcase",
    author: mockUsers[3],
    gradient: "from-rose-600 to-orange-600",
  },
];

export const mockVibingItems: VibingItem[] = [
  {
    id: "v1",
    title: "Claude 3.5 vs GPT-4 Turbo benchmarks",
    author: mockUsers[0],
    trend: "up",
    engagement: 2340,
  },
  {
    id: "v2",
    title: "New Stable Diffusion 3 release notes",
    author: mockUsers[1],
    trend: "up",
    engagement: 1890,
  },
  {
    id: "v3",
    title: "AI regulation update: EU AI Act",
    author: mockUsers[2],
    trend: "stable",
    engagement: 1560,
  },
];

export const mockCampaign: Campaign = {
  id: "c1",
  title: "AI Creator Challenge",
  description: "Build the most innovative AI-powered tool and win prizes worth $50,000",
  sponsor: "TechCorp",
  sponsorLogo: "https://api.dicebear.com/7.x/shapes/svg?seed=techcorp",
  endDate: "2024-02-15",
  prize: "$50,000",
  participants: 1234,
  gradient: "from-indigo-500 via-purple-500 to-pink-500",
};

export function generateMoreDiscussions(page: number): Discussion[] {
  return mockDiscussions.map((discussion, index) => ({
    ...discussion,
    id: `${discussion.id}-page${page}-${index}`,
    title: `[Page ${page}] ${discussion.title}`,
    upvotes: discussion.upvotes + Math.floor(Math.random() * 100),
    comments: discussion.comments + Math.floor(Math.random() * 20),
  }));
}
